//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.08 at 05:40:44 PM IST 
//


package hmh.rs.pojo;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public class Error {

	/**
	 * Error category
	 */	
    protected String errorCategory;
	/**
	 * Error code
	 */	
    protected String errorCode;
	/**
	 * Error message
	 */	
    protected String errorMessage;
	/**
	 * Refers to the item where error occurred
	 */	
	protected String itemKey;
    protected String targetSystemError;

    
    public Error() {}
    
    public Error(String errorCode, String errorMessage) {
    	this.errorCode = errorCode;
    	this.errorMessage = errorMessage;
    }
    
    public Error(String errorCategory, String errorCode, String errorMessage) {
    	this.errorCategory = errorCategory;
    	this.errorCode = errorCode;
    	this.errorMessage = errorMessage;
    }
    
    
    public String getTargetSystemError() {
		return targetSystemError;
	}

	public void setTargetSystemError(String targetSystemError) {
		this.targetSystemError = targetSystemError;
	}

	public String getErrorCategory() {
        return errorCategory;
    }
    
    public void setErrorCategory(String value) {
        this.errorCategory = value;
    }
    
    public String getErrorCode() {
        return errorCode;
    }
    
    public void setErrorCode(String value) {
        this.errorCode = value;
    }
    
    public String getErrorMessage() {
        return errorMessage;
    }
    
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

	public String getItemKey() {
		return itemKey;
	}

	public void setItemKey(String itemKey) {
		this.itemKey = itemKey;
	}

}
